id: P007889
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30146
  title: གངས་ཤུག་མ་ཎི་ལོ་ཆེན་རིག་འཛིན་ཆོས་ཉིད་བཟང་མོའི་རྣམ་པར་ཐར་པ་རྣམ་མཁྱེན་བདེ་སྟེར
  author: ''
  volumes:
    be0d6303ec774ee696b7e637154749cb:
      image_group_id: I5925
      title: ''
      volume_number: 1
      total_pages: 572
      base_file: v001.txt
