id: P007889
initial_creation_type: ocr
source_metadata:
  id: bdr:W30146
  title: གངས་ཤུག་མ་ཎི་ལོ་ཆེན་རིག་འཛིན་ཆོས་ཉིད་བཟང་མོའི་རྣམ་པར་ཐར་པ་རྣམ་མཁྱེན་བདེ་སྟེར
  author: ''
  volumes:
    b2f163cb3f2c4519a516cfa4af5b7e89:
      image_group_id: I5925
      title: ''
      volume_number: 1
      total_pages: 572
ebook_metadata:
  title: གངས་ཤུག་མ་ཎི་ལོ་ཆེན་རིག་འཛིན་ཆོས་ཉིད་བཟང་མོའི་རྣམ་པར་ཐར་པ་རྣམ་མཁྱེན་བདེ་སྟེར
  author: ''
  sku: P007889
  cover: cover.jpg
  layers:
  - pagination
