id: I14431498
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:59:43+00:00'
last_modified: '2022-06-09T07:06:29.034906+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30146
  title: གངས་ཤུག་མ་ཎི་ལོ་ཆེན་རིག་འཛིན་ཆོས་ཉིད་བཟང་མོའི་རྣམ་པར་ཐར་པ་རྣམ་མཁྱེན་བདེ་སྟེར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D93C:
      image_group_id: I5925
      title: ''
      total_pages: 572
      order: 1
      base_file: D93C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
